# Generated by Django 4.1.7 on 2023-03-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
